language: python
python:
        - '3.5'

before_script: 

        - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="disquaire_project.settings"

services: 
        - postgresql

env: DJANGO_SETTINGS_MODULE="disquaire_project.settings.travis"

script:
        - ./manage.py test

branches:
        only:
                - staging
